DEFAULT_MIN_PRICE = 1
DEFAULT_PRICE = 1

DEFAULT_MAX_SCHEDULE_LIFETIME_HRS = 8
DEFAULT_MAX_SCHEDULE_LIFETIME_SEC = DEFAULT_MAX_SCHEDULE_LIFETIME_HRS * 3

DEFAULT_MAX_RIDE_LIFETIME_HRS = 8
DEFAULT_MAX_RIDE_LIFETIME_SEC = DEFAULT_MAX_RIDE_LIFETIME_HRS * 3600

DEFAULT_MAX_DELAY_TIME_SEARCH_LOCATION = 1, 3

DEFAULT_DELAY_TIME_NOTIFY = 5
