services:
  api:
    build: .
    container_name: esturide-api-pico
    hostname: esturide-api
    image: esturide-api:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - .:/docs
    networks:
      - net

volumes:
  db_data:
  docs:

networks:
  net:
    driver: bridge
